name: Daily NFL Data to S3

on:
  schedule:
    - cron: "15 10 * * *"   # Runs every day at 10:15 UTC
  workflow_dispatch:         # Allows manual runs from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          NFL_S3_BUCKET: ${{ secrets.NFL_S3_BUCKET }}
          DATA_SEASONS: ${{ secrets.DATA_SEASONS || 'current' }}
          INCLUDE_PBP: ${{ secrets.INCLUDE_PBP || 'false' }}
        run: |
          python pipeline.py
